version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/codingagent
      - REDIS_URL=redis://redis:6379
      - NOTION_API_KEY=${NOTION_API_KEY}
      - VERCEL_TOKEN=${VERCEL_TOKEN}

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=codingagent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@codingagent.local
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
  redis-data:

