import * as vscode from 'vscode';
import { ConfigManager } from '../utils/configManager';
import { ApiClient } from '../utils/apiClient';

export class CodeOptimizer {
    constructor(
        private context: vscode.ExtensionContext,
        private configManager: ConfigManager,
        private apiClient: ApiClient
    ) {}

    async optimizeCode(): Promise<void> {
        const editor = vscode.window.activeTextEditor;
        if (!editor) {
            vscode.window.showWarningMessage('No active editor found');
            return;
        }

        const selection = editor.selection;
        const document = editor.document;
        
        // Get selected text or entire document if no selection
        const code = selection.isEmpty 
            ? document.getText() 
            : document.getText(selection);

        if (!code.trim()) {
            vscode.window.showWarningMessage('No code selected to optimize');
            return;
        }

        // Show progress
        await vscode.window.withProgress({
            location: vscode.ProgressLocation.Notification,
            title: "Optimizing code...",
            cancellable: true
        }, async (progress, token) => {
            try {
                const response = await this.apiClient.optimizeCode(
                    code,
                    this.getLanguageFromDocument(document)
                );

                if (token.isCancellationRequested) {
                    return;
                }

                if (response.success && response.data?.optimizations) {
                    await this.showOptimizations(response.data.optimizations, editor, selection);
                } else {
                    vscode.window.showErrorMessage(`Failed to optimize code: ${response.error}`);
                }
            } catch (error) {
                vscode.window.showErrorMessage(`Error optimizing code: ${error}`);
            }
        });
    }

    private async showOptimizations(optimizations: any[], editor: vscode.TextEditor, selection: vscode.Selection): Promise<void> {
        if (optimizations.length === 0) {
            vscode.window.showInformationMessage('No optimizations found. Your code is already well-optimized!');
            return;
        }

        // Create quick pick items for optimizations
        const items = optimizations.map((optimization, index) => ({
            label: `${optimization.type?.toUpperCase() || 'OPTIMIZATION'}: ${optimization.title}`,
            description: optimization.description,
            detail: `Impact: ${optimization.impact || 'Medium'} | Effort: ${optimization.effort || 'Low'}`,
            optimization: optimization
        }));

        const selected = await vscode.window.showQuickPick(items, {
            placeHolder: 'Select an optimization to apply',
            canPickMany: false
        });

        if (selected) {
            await this.applyOptimization(selected.optimization, editor, selection);
        }
    }

    private async applyOptimization(optimization: any, editor: vscode.TextEditor, selection: vscode.Selection): Promise<void> {
        const { originalCode, optimizedCode, title, description } = optimization;

        // Show optimization preview
        const apply = await vscode.window.showInformationMessage(
            `Apply optimization: ${title}`,
            'Preview Changes',
            'Apply',
            'Cancel'
        );

        if (apply === 'Cancel') {
            return;
        }

        if (apply === 'Preview Changes') {
            await this.showOptimizationPreview(originalCode, optimizedCode, title, description);
            return;
        }

        if (apply === 'Apply') {
            await this.applyChanges(optimizedCode, editor, selection);
        }
    }

    private async showOptimizationPreview(originalCode: string, optimizedCode: string, title: string, description: string): Promise<void> {
        // Create a new document to show the optimization
        const doc = await vscode.workspace.openTextDocument({
            content: `# ${title}

## Description
${description}

## Original Code
\`\`\`typescript
${originalCode}
\`\`\`

## Optimized Code
\`\`\`typescript
${optimizedCode}
\`\`\`

## Benefits
- Improved performance
- Better readability
- Reduced complexity
- Enhanced maintainability

---
*Optimization generated by Coding Agent*`,
            language: 'markdown'
        });

        await vscode.window.showTextDocument(doc);
    }

    private async applyChanges(optimizedCode: string, editor: vscode.TextEditor, selection: vscode.Selection): Promise<void> {
        const edit = new vscode.WorkspaceEdit();
        
        if (selection.isEmpty) {
            // Replace entire document
            edit.replace(editor.document.uri, new vscode.Range(0, 0, editor.document.lineCount, 0), optimizedCode);
        } else {
            // Replace selected text
            edit.replace(editor.document.uri, selection, optimizedCode);
        }

        const applied = await vscode.workspace.applyEdit(edit);
        
        if (applied) {
            vscode.window.showInformationMessage('Code optimization applied successfully!');
        } else {
            vscode.window.showErrorMessage('Failed to apply optimization');
        }
    }

    private getLanguageFromDocument(document: vscode.TextDocument): string {
        const languageMap: { [key: string]: string } = {
            'typescript': 'typescript',
            'javascript': 'javascript',
            'python': 'python',
            'java': 'java',
            'go': 'go',
            'rust': 'rust',
            'cpp': 'cpp',
            'c': 'c',
            'csharp': 'csharp',
            'php': 'php',
            'ruby': 'ruby',
            'swift': 'swift',
            'kotlin': 'kotlin'
        };

        return languageMap[document.languageId] || 'unknown';
    }
}
