name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install CLI deps
        working-directory: cli
        run: |
          npm ci || npm install
      - name: Lint/build CLI
        working-directory: cli
        run: |
          npm run -s build || echo "no build script"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install server deps
        working-directory: server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Unit tests placeholder
        run: echo "Add tests under tests/ and wire runners"
